# From imagenet_feat_v3
# This is used as default.
RUN_NAME: 'imagenet_v3'

SEED: 42

DATASET:
  NAME: 'imagenet'
  TRANSFORM_NAME: 'imagenet'
  ROOT_DIR: '../data/ImageNet'

DATALOADER:
  BATCH_SIZE: 2048
  WORKERS: 8

EPOCHS: 10

MODEL:
  ARCH: 'resnet50'
  PRETRAIN_PATH: 'pretrained/pretext_imagenet/model.pth.tar'
  BACKBONE_DIM: 2048

USLT_PRETRAIN:
  TOPK_NEIGHBORS_PATH: 'pretrained/pretext_imagenet/topk-train-neighbors.npy'
  NUM_NEIGHBORS: 20
  # There could be empty selections in the clusters.
  NUM_SELECTED_SAMPLES: 3000
  # Avoid instability
  LOCAL_LOSS_SCALE: 0.5
  ADJUSTMENT_WEIGHT: 2.5
  SHARPEN_TEMPERATURE: 0.5
  CONFIDENCE_THRESHOLD: 0.0
  REWEIGHT: False
  EMA_DECAY: 0.0
  # Enabled if number of classes in the dataset is at least 100
  MEAN_OUTSIDE_MASK: True
  # Frozen backbone for ImageNet
  UPDATE_HEAD_ONLY: True
  TURN_OFF_LOCAL_LOSS_AFTER_EPOCH: 100.0
  COUNT_EMA_MIN_TH: 100
  COUNT_EMA_MAX_TH: 1000
  REASSIGN_AFTER_STEPS: 1250
